Breaking down files to MVC structure
dpointk/disko pull request #12
Opened 2024-03-21 17:01 UTC by Daniel-Shwartzman

Removed amount column, created mvc structure with basic functions for controller and view, modified disco.py to run the new changes.

2024-03-22 14:47 UTC, dpointk commented on disko.py
> +from src.mvc.view import ImageRegistryManager
let's leave the structure with src.disko.xx.xxx as it's important for future integration. @Daniel-Shwartzman 
also change the mvc folder to something else.

2024-03-22 14:47 UTC, dpointk commented on src/mvc/controller.py
The file name is controller.py , please change to image_controller.py

2024-03-22 14:47 UTC, dpointk commented on src/mvc/model.py
also here , please change to image_model.py

2024-03-22 14:47 UTC, dpointk commented on src/mvc/view.py
change filename to image_view.py

2024-03-23 21:49 UTC, dpointk requested changes
Please check my comments in the view and main section

2024-03-23 21:49 UTC, dpointk commented on disko.py
> +    gui.run()
There's a different approach we would like to achieve.
The way it is built in your commit now, is that the controlling of what happens is I the view. It should be in the controller.
The controller should gather all the information and send it to the view.
The way you have structured it here is that the view is in charge. We should change it.
The idea is that the view should be replaceable tomorrow. So no logic should happen there. All should happen in the controller.

2024-03-23 21:49 UTC, dpointk commented on src/disko/image_management/image_view.py
> +    def run(self):
This function should get all the required data from the controller which it I turn should run it.
The main python script will run a function in the controller which will decide how to output the data.

2024-03-23 21:49 UTC, dpointk commented on src/disko/image_management/image_view.py
> +        cluster_names = self.controller.get_kubernetes_clusters()
This should be given as a parameter from the controller.

2024-03-26 18:41 UTC, Daniel-Shwartzman commented
We would like your help, we cannot entirley resolve the import situation, this is the error we get with the current commit:
Traceback (most recent call last):
  File "/home/daniel/Desktop/disko/disko.py", line 2, in <module>
    from src.disko.image_management.image_controller import ImageController
  File "/home/daniel/Desktop/disko/src/disko/image_management/image_controller.py", line 4, in <module>
    from src.disko.image_management.image_view import ImageRegistryManager
  File "/home/daniel/Desktop/disko/src/disko/image_management/image_view.py", line 4, in <module>
    from src.disko.image_management.image_controller import ImageController
ImportError: cannot import name 'ImageController' from partially initialized module 'src.disko.image_management.image_controller' (most likely due to a circular import) (/home/daniel/Desktop/disko/src/disko/image_management/image_controller.py)

2024-03-27 08:58 UTC, dpointk commented
You're not supposed to import the image controller in the view.
The only function of the view is to print the output.
I think the fact that you're using this tk to manage buttons and manage the application is the issue. In this case it is best to have a separated approach from gui and controller. For example. Two applications.

2024-03-27 09:16 UTC, dpointk commented
See this answer and comment about PySide

https://stackoverflow.com/questions/38042632/mvc-the-simplest-example

2024-03-27 11:14 UTC, Daniel-Shwartzman commented
To fix the import error we removed the cluster selection option, so the scanning happens on the current cluster.
The view does not contain the controller, the controller runs the view.

2024-05-02 11:10 UTC, closed without merging